In [1]:
import numpy as np
import pandas as pd

In [23]:
## load the PPC Campaign Performance Dataset
df = pd.read_excel(r"C:\Users\aluis\OneDrive\Desktop\PPC_Data\ppc_campaign_performance_data.xlsx")

In [27]:
### peek into the data
df.head(20)

,Campaign_ID,Budget,Clicks,CTR,CPC,Conversions,CPA,Conversion_Rate,Duration,Platform,Content_Type,Target_Age,Target_Gender,Region,Revenue,Spend,ROAS,Date,Impressions
0,C3578,6390,401,0.0461,15.94,174,36.72,0.4339,20,Instagram,Carousel,35-44,Male,Europe,27840,6453.9,4.31,2025-01-19,8698
1,C6702,9870,1286,0.2860,7.67,821,12.02,0.6384,28,LinkedIn,Text,55+,Male,Africa,128076,10067.4,12.72,2025-01-22,4496
2,C9725,7700,1684,0.2122,4.57,1060,7.26,0.6295,15,Instagram,Video,35-44,Other,North America,193980,7623.0,25.45,2024-07-23,7935
3,C9472,8420,444,0.0961,18.96,308,27.34,0.6937,25,Google,Text,25-34,Male,North America,24024,8504.2,2.82,2024-04-20,4620
4,C7601,8470,1912,0.3652,4.43,1428,5.93,0.7469,9,Google,Text,25-34,Other,Europe,277032,8046.5,34.43,2024-08-07,5235
5,C2793,5450,663,0.0932,8.22,605,9.01,0.9125,20,YouTube,Text,45-54,Other,South America,21780,5177.5,4.21,2024-05-04,7113
6,C8817,4420,1044,0.2902,4.23,452,9.78,0.4330,13,Instagram,Text,25-34,Male,Europe,51528,4508.4,11.43,2024-08-09,3597
7,C1097,7720,1001,0.1036,7.71,916,8.43,0.9151,19,YouTube,Video,18-24,Other,North America,71448,7334.0,9.74,2024-05-19,9662
8,C9333,2070,379,0.0536,5.46,192,10.78,0.5066,29,LinkedIn,Video,25-34,Male,Africa,15744,2111.4,7.46,2024-06-16,7070
9,C1232,2710,83,0.0096,32.65,54,50.19,0.6506,23,YouTube,Image,35-44,Other,Africa,7236,2628.7,2.75,2024-11-04,8645
10,C2507,3500,1248,0.2322,2.80,556,6.29,0.4455,10,Facebook,Carousel,55+,Male,South America,97856,3500.0,27.96,2024-09-16,5374
11,C7297,2250,208,0.0254,10.82,13,173.08,0.0625,19,Google,Carousel,25-34,Female,South America,598,2137.5,0.28,2024-03-10,8188
12,C4133,7460,1326,0.1529,5.63,154,48.44,0.1161,25,YouTube,Carousel,55+,Female,Europe,22792,7609.2,3.00,2024-07-06,8672
13,C5129,9490,1391,0.1627,6.82,1288,7.37,0.9260,9,Facebook,Text,55+,Male,South America,136528,9774.7,13.97,2024-11-16,8549
14,C2514,2810,1491,0.1635,1.88,1068,2.63,0.7163,30,Facebook,Video,55+,Male,North America,206124,2950.5,69.86,2024-06-10,9119
15,C8001,3300,1765,0.2958,1.87,454,7.27,0.2572,28,YouTube,Video,18-24,Other,Asia,86260,3168.0,27.23,2024-07-19,5966
16,C1589,9370,1696,0.2854,5.52,790,11.86,0.4658,21,Facebook,Text,55+,Male,Asia,120080,9088.9,13.21,2024-07-25,5942
17,C6840,3290,376,0.1717,8.75,115,28.61,0.3059,9,Google,Video,55+,Male,South America,17020,3388.7,5.02,2024-09-16,2189
18,C9831,9800,544,0.0781,18.01,62,158.06,0.1140,23,Instagram,Carousel,45-54,Female,North America,8618,9800.0,0.88,2024-03-22,6965
19,C2679,8760,419,0.0892,20.91,251,34.90,0.5990,11,Instagram,Video,18-24,Other,Asia,42419,8409.6,5.04,2024-04-19,4697

In [37]:
# get overview of dataset structure
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   campaign_id      1000 non-null   object
 1   budget           1000 non-null   int64
 2   clicks           1000 non-null   int64
 3   ctr              1000 non-null   float64
 4   cpc              1000 non-null   float64
 5   conversions      1000 non-null   int64
 6   cpa              1000 non-null   float64
 7   conversion_rate  1000 non-null   float64
 8   duration         1000 non-null   int64
 9   platform         1000 non-null   object
 10  content_type     1000 non-null   object
 11  target_age       1000 non-null   object
 12  target_gender    1000 non-null   object
 13  region           1000 non-null   object
 14  revenue          1000 non-null   int64
 15  spend            1000 non-null   float64
 16  roas             1000 non-null   float64
 17  date             1000 non-null   object
 18  impressions      1000 non-null   int64
dtypes: float64(6), int64(6), object(7)
memory usage: 148.6+ KB

In [31]:
## check for missing values
df.isnull().sum()

Campaign_ID        0
Budget             0
Clicks             0
CTR                0
CPC                0
Conversions        0
CPA                0
Conversion_Rate    0
Duration           0
Platform           0
Content_Type       0
Target_Age         0
Target_Gender      0
Region             0
Revenue            0
Spend              0
ROAS               0
Date               0
Impressions        0
dtype: int64

In [47]:
# now we standardize our column names
# we will remove leading spaces, convert to lowercase, and replace spaces with underscores for column names
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df

,campaign_id,budget,clicks,ctr,cpc,conversions,cpa,conversion_rate,duration,platform,content_type,target_age,target_gender,region,revenue,spend,roas,date,impressions
0,C3578,6390,401,0.0461,15.94,174,36.72,0.4339,20,Instagram,Carousel,35-44,Male,Europe,27840,6453.9,4.31,2025-01-19,8698
1,C6702,9870,1286,0.2860,7.67,821,12.02,0.6384,28,LinkedIn,Text,55+,Male,Africa,128076,10067.4,12.72,2025-01-22,4496
2,C9725,7700,1684,0.2122,4.57,1060,7.26,0.6295,15,Instagram,Video,35-44,Other,North America,193980,7623.0,25.45,2024-07-23,7935
3,C9472,8420,444,0.0961,18.96,308,27.34,0.6937,25,Google,Text,25-34,Male,North America,24024,8504.2,2.82,2024-04-20,4620
4,C7601,8470,1912,0.3652,4.43,1428,5.93,0.7469,9,Google,Text,25-34,Other,Europe,277032,8046.5,34.43,2024-08-07,5235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,C4071,7400,657,0.0986,11.26,136,54.41,0.2070,27,Facebook,Carousel,18-24,Other,Europe,24072,7696.0,3.13,2024-08-15,6663
996,C2402,3670,1534,0.1974,2.39,1258,2.92,0.8201,26,LinkedIn,Video,18-24,Other,Asia,206312,3523.2,58.56,2024-11-08,7771
997,C3257,4820,231,0.0238,20.87,83,58.07,0.3593,20,Google,Video,55+,Other,North America,5146,5061.0,1.02,2025-01-16,9705
998,C4315,9330,395,0.0517,23.62,239,39.04,0.6051,26,Instagram,Image,55+,Other,Europe,35372,8956.8,3.95,2025-01-26,7640
999,C1412,3070,493,0.1965,6.23,415,7.40,0.8418,10,Instagram,Carousel,25-34,Other,Asia,41915,3192.8,13.13,2024-02-22,2508

In [49]:
# remove leading spaces from data values in dataset
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip()
df

,campaign_id,budget,clicks,ctr,cpc,conversions,cpa,conversion_rate,duration,platform,content_type,target_age,target_gender,region,revenue,spend,roas,date,impressions
0,C3578,6390,401,0.0461,15.94,174,36.72,0.4339,20,Instagram,Carousel,35-44,Male,Europe,27840,6453.9,4.31,2025-01-19,8698
1,C6702,9870,1286,0.2860,7.67,821,12.02,0.6384,28,LinkedIn,Text,55+,Male,Africa,128076,10067.4,12.72,2025-01-22,4496
2,C9725,7700,1684,0.2122,4.57,1060,7.26,0.6295,15,Instagram,Video,35-44,Other,North America,193980,7623.0,25.45,2024-07-23,7935
3,C9472,8420,444,0.0961,18.96,308,27.34,0.6937,25,Google,Text,25-34,Male,North America,24024,8504.2,2.82,2024-04-20,4620
4,C7601,8470,1912,0.3652,4.43,1428,5.93,0.7469,9,Google,Text,25-34,Other,Europe,277032,8046.5,34.43,2024-08-07,5235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,C4071,7400,657,0.0986,11.26,136,54.41,0.2070,27,Facebook,Carousel,18-24,Other,Europe,24072,7696.0,3.13,2024-08-15,6663
996,C2402,3670,1534,0.1974,2.39,1258,2.92,0.8201,26,LinkedIn,Video,18-24,Other,Asia,206312,3523.2,58.56,2024-11-08,7771
997,C3257,4820,231,0.0238,20.87,83,58.07,0.3593,20,Google,Video,55+,Other,North America,5146,5061.0,1.02,2025-01-16,9705
998,C4315,9330,395,0.0517,23.62,239,39.04,0.6051,26,Instagram,Image,55+,Other,Europe,35372,8956.8,3.95,2025-01-26,7640
999,C1412,3070,493,0.1965,6.23,415,7.40,0.8418,10,Instagram,Carousel,25-34,Other,Asia,41915,3192.8,13.13,2024-02-22,2508

In [53]:
# Convert date column from object data type to datetime data type and validate dates
df['date'] = pd.to_datetime(df['date'], errors='coerce')

In [59]:
# check to see number of invalid dates after conversion
df['date'].isna().sum()

0

In [65]:
# converting date back to string for MYSQL data import
df['date'] = df['date'].dt.strftime('%Y-%m-%d')

AttributeError: Can only use .dt accessor with datetimelike values

In [67]:
df

,campaign_id,budget,clicks,ctr,cpc,conversions,cpa,conversion_rate,duration,platform,content_type,target_age,target_gender,region,revenue,spend,roas,date,impressions
0,C3578,6390,401,0.0461,15.94,174,36.72,0.4339,20,Instagram,Carousel,35-44,Male,Europe,27840,6453.9,4.31,2025-01-19,8698
1,C6702,9870,1286,0.2860,7.67,821,12.02,0.6384,28,LinkedIn,Text,55+,Male,Africa,128076,10067.4,12.72,2025-01-22,4496
2,C9725,7700,1684,0.2122,4.57,1060,7.26,0.6295,15,Instagram,Video,35-44,Other,North America,193980,7623.0,25.45,2024-07-23,7935
3,C9472,8420,444,0.0961,18.96,308,27.34,0.6937,25,Google,Text,25-34,Male,North America,24024,8504.2,2.82,2024-04-20,4620
4,C7601,8470,1912,0.3652,4.43,1428,5.93,0.7469,9,Google,Text,25-34,Other,Europe,277032,8046.5,34.43,2024-08-07,5235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,C4071,7400,657,0.0986,11.26,136,54.41,0.2070,27,Facebook,Carousel,18-24,Other,Europe,24072,7696.0,3.13,2024-08-15,6663
996,C2402,3670,1534,0.1974,2.39,1258,2.92,0.8201,26,LinkedIn,Video,18-24,Other,Asia,206312,3523.2,58.56,2024-11-08,7771
997,C3257,4820,231,0.0238,20.87,83,58.07,0.3593,20,Google,Video,55+,Other,North America,5146,5061.0,1.02,2025-01-16,9705
998,C4315,9330,395,0.0517,23.62,239,39.04,0.6051,26,Instagram,Image,55+,Other,Europe,35372,8956.8,3.95,2025-01-26,7640
999,C1412,3070,493,0.1965,6.23,415,7.40,0.8418,10,Instagram,Carousel,25-34,Other,Asia,41915,3192.8,13.13,2024-02-22,2508

In [69]:
# check for duplicate rows
df.duplicated().sum()

0

In [71]:
# resetting index
df.reset_index(drop=True, inplace=True)

In [73]:
df

,campaign_id,budget,clicks,ctr,cpc,conversions,cpa,conversion_rate,duration,platform,content_type,target_age,target_gender,region,revenue,spend,roas,date,impressions
0,C3578,6390,401,0.0461,15.94,174,36.72,0.4339,20,Instagram,Carousel,35-44,Male,Europe,27840,6453.9,4.31,2025-01-19,8698
1,C6702,9870,1286,0.2860,7.67,821,12.02,0.6384,28,LinkedIn,Text,55+,Male,Africa,128076,10067.4,12.72,2025-01-22,4496
2,C9725,7700,1684,0.2122,4.57,1060,7.26,0.6295,15,Instagram,Video,35-44,Other,North America,193980,7623.0,25.45,2024-07-23,7935
3,C9472,8420,444,0.0961,18.96,308,27.34,0.6937,25,Google,Text,25-34,Male,North America,24024,8504.2,2.82,2024-04-20,4620
4,C7601,8470,1912,0.3652,4.43,1428,5.93,0.7469,9,Google,Text,25-34,Other,Europe,277032,8046.5,34.43,2024-08-07,5235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,C4071,7400,657,0.0986,11.26,136,54.41,0.2070,27,Facebook,Carousel,18-24,Other,Europe,24072,7696.0,3.13,2024-08-15,6663
996,C2402,3670,1534,0.1974,2.39,1258,2.92,0.8201,26,LinkedIn,Video,18-24,Other,Asia,206312,3523.2,58.56,2024-11-08,7771
997,C3257,4820,231,0.0238,20.87,83,58.07,0.3593,20,Google,Video,55+,Other,North America,5146,5061.0,1.02,2025-01-16,9705
998,C4315,9330,395,0.0517,23.62,239,39.04,0.6051,26,Instagram,Image,55+,Other,Europe,35372,8956.8,3.95,2025-01-26,7640
999,C1412,3070,493,0.1965,6.23,415,7.40,0.8418,10,Instagram,Carousel,25-34,Other,Asia,41915,3192.8,13.13,2024-02-22,2508

In [75]:
# Export clean file as CSV for MYSQL
df.to_csv("ppc_campaign_cleaned.csv", index=False)