In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\aluis\OneDrive\Desktop\Google_Project\ppc_campaign_cleaned.csv")

In [3]:
df

,campaign_id,budget,clicks,ctr,cpc,conversions,cpa,conversion_rate,duration,platform,content_type,target_age,target_gender,region,revenue,spend,roas,date,impressions
0,C3578,6390,401,0.0461,15.94,174,36.72,0.4339,20,Instagram,Carousel,35-44,Male,Europe,27840,6453.9,4.31,2025-01-19,8698
1,C6702,9870,1286,0.2860,7.67,821,12.02,0.6384,28,LinkedIn,Text,55+,Male,Africa,128076,10067.4,12.72,2025-01-22,4496
2,C9725,7700,1684,0.2122,4.57,1060,7.26,0.6295,15,Instagram,Video,35-44,Other,North America,193980,7623.0,25.45,2024-07-23,7935
3,C9472,8420,444,0.0961,18.96,308,27.34,0.6937,25,Google,Text,25-34,Male,North America,24024,8504.2,2.82,2024-04-20,4620
4,C7601,8470,1912,0.3652,4.43,1428,5.93,0.7469,9,Google,Text,25-34,Other,Europe,277032,8046.5,34.43,2024-08-07,5235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,C4071,7400,657,0.0986,11.26,136,54.41,0.2070,27,Facebook,Carousel,18-24,Other,Europe,24072,7696.0,3.13,2024-08-15,6663
996,C2402,3670,1534,0.1974,2.39,1258,2.92,0.8201,26,LinkedIn,Video,18-24,Other,Asia,206312,3523.2,58.56,2024-11-08,7771
997,C3257,4820,231,0.0238,20.87,83,58.07,0.3593,20,Google,Video,55+,Other,North America,5146,5061.0,1.02,2025-01-16,9705
998,C4315,9330,395,0.0517,23.62,239,39.04,0.6051,26,Instagram,Image,55+,Other,Europe,35372,8956.8,3.95,2025-01-26,7640
999,C1412,3070,493,0.1965,6.23,415,7.40,0.8418,10,Instagram,Carousel,25-34,Other,Asia,41915,3192.8,13.13,2024-02-22,2508

In [4]:
df.campaign_id.nunique()

954

In [5]:
df.shape

(1000, 19)

In [6]:
duplicate_ids = df['campaign_id'][df['campaign_id'].duplicated()]

In [7]:
duplicate_ids.shape

(46,)

In [8]:
df.platform.nunique()

5

In [38]:
df[['campaign_id','spend','cpa','roas']]

    campaign_id    spend    cpa   roas
0         C3578   6453.9  36.72   4.31
1         C6702  10067.4  12.02  12.72
2         C9725   7623.0   7.26  25.45
3         C9472   8504.2  27.34   2.82
4         C7601   8046.5   5.93  34.43
..          ...      ...    ...    ...
995       C4071   7696.0  54.41   3.13
996       C2402   3523.2   2.92  58.56
997       C3257   5061.0  58.07   1.02
998       C4315   8956.8  39.04   3.95
999       C1412   3192.8   7.40  13.13

[1000 rows x 4 columns]

In [80]:
df[df['campaign_id'].duplicated(keep=False)]

,campaign_id,budget,clicks,ctr,cpc,conversions,cpa,conversion_rate,duration,platform,content_type,target_age,target_gender,region,revenue,spend,roas,date,impressions
1,C6702,9870,1286,0.2860,7.67,821,12.02,0.6384,28,LinkedIn,Text,55+,Male,Africa,128076,10067.4,12.72,2025-01-22,4496
2,C9725,7700,1684,0.2122,4.57,1060,7.26,0.6295,15,Instagram,Video,35-44,Other,North America,193980,7623.0,25.45,2024-07-23,7935
12,C4133,7460,1326,0.1529,5.63,154,48.44,0.1161,25,YouTube,Carousel,55+,Female,Europe,22792,7609.2,3.00,2024-07-06,8672
17,C6840,3290,376,0.1717,8.75,115,28.61,0.3059,9,Google,Video,55+,Male,South America,17020,3388.7,5.02,2024-09-16,2189
20,C9010,4120,1076,0.1946,3.83,1027,4.01,0.9545,11,Instagram,Video,45-54,Male,South America,186914,3914.0,47.76,2024-06-04,5529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,C9240,2720,1253,0.2487,2.17,865,3.14,0.6903,21,Facebook,Carousel,35-44,Other,South America,55360,2747.2,20.15,2024-11-20,5038
967,C3516,8740,1264,0.1546,6.91,734,11.91,0.5807,21,LinkedIn,Video,35-44,Other,South America,27892,8303.0,3.36,2024-09-06,8175
972,C6242,9170,1005,0.1830,9.12,199,46.08,0.1980,13,Instagram,Text,18-24,Other,Europe,20099,9170.0,2.19,2024-12-29,5491
976,C8156,5160,279,0.0287,18.49,77,67.01,0.2760,13,LinkedIn,Text,35-44,Female,Asia,8624,5418.0,1.59,2024-03-27,9721
982,C2710,2290,1620,0.5633,1.41,398,5.75,0.2457,7,Google,Carousel,55+,Female,Africa,11940,2358.7,5.06,2024-04-29,2875

In [82]:
df['campaign_id'] = df['campaign_id'] + '_' + df.groupby('campaign_id').cumcount().astype(str)

In [84]:
df

,campaign_id,budget,clicks,ctr,cpc,conversions,cpa,conversion_rate,duration,platform,content_type,target_age,target_gender,region,revenue,spend,roas,date,impressions
0,C3578_0,6390,401,0.0461,15.94,174,36.72,0.4339,20,Instagram,Carousel,35-44,Male,Europe,27840,6453.9,4.31,2025-01-19,8698
1,C6702_0,9870,1286,0.2860,7.67,821,12.02,0.6384,28,LinkedIn,Text,55+,Male,Africa,128076,10067.4,12.72,2025-01-22,4496
2,C9725_0,7700,1684,0.2122,4.57,1060,7.26,0.6295,15,Instagram,Video,35-44,Other,North America,193980,7623.0,25.45,2024-07-23,7935
3,C9472_0,8420,444,0.0961,18.96,308,27.34,0.6937,25,Google,Text,25-34,Male,North America,24024,8504.2,2.82,2024-04-20,4620
4,C7601_0,8470,1912,0.3652,4.43,1428,5.93,0.7469,9,Google,Text,25-34,Other,Europe,277032,8046.5,34.43,2024-08-07,5235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,C4071_0,7400,657,0.0986,11.26,136,54.41,0.2070,27,Facebook,Carousel,18-24,Other,Europe,24072,7696.0,3.13,2024-08-15,6663
996,C2402_0,3670,1534,0.1974,2.39,1258,2.92,0.8201,26,LinkedIn,Video,18-24,Other,Asia,206312,3523.2,58.56,2024-11-08,7771
997,C3257_0,4820,231,0.0238,20.87,83,58.07,0.3593,20,Google,Video,55+,Other,North America,5146,5061.0,1.02,2025-01-16,9705
998,C4315_0,9330,395,0.0517,23.62,239,39.04,0.6051,26,Instagram,Image,55+,Other,Europe,35372,8956.8,3.95,2025-01-26,7640
999,C1412_0,3070,493,0.1965,6.23,415,7.40,0.8418,10,Instagram,Carousel,25-34,Other,Asia,41915,3192.8,13.13,2024-02-22,2508

In [86]:
df['campaign_id'].nunique()

1000

In [100]:
df.describe()

,budget,clicks,ctr,cpc,conversions,cpa,conversion_rate,duration,revenue,spend,roas,impressions
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,5961.990000,1013.229000,0.258417,11.230730,505.67200,40.966170,0.508329,18.313000,59886.710000,5956.167800,11.689180,5497.177000
std,2326.091753,563.971223,0.262449,16.026811,424.76226,76.623075,0.284814,6.952796,60237.650065,2330.082996,13.173887,2576.010494
min,2030.000000,50.000000,0.006100,1.080000,10.00000,1.670000,0.009600,7.000000,598.000000,1928.500000,0.070000,1000.000000
25%,4007.500000,514.250000,0.094275,3.707500,153.75000,7.157500,0.267000,12.000000,15111.250000,4031.475000,2.717500,3262.750000
50%,5855.000000,996.500000,0.182150,5.755000,396.50000,14.245000,0.517150,18.000000,39378.000000,5843.650000,7.295000,5410.000000
75%,7960.000000,1491.500000,0.306900,11.285000,772.25000,36.840000,0.751675,24.000000,86009.000000,7994.850000,15.552500,7719.750000
max,9990.000000,1996.000000,1.785100,132.310000,1894.00000,733.080000,1.000000,30.000000,320788.000000,10468.500000,93.900000,10000.000000

In [94]:
df['campaign_id'].duplicated().sum()  # just IDs

0

In [114]:
df.to_csv('ppc_campaign_clean_2.0.csv', index=False)